// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_home
void ui_home_screen_init(void);
lv_obj_t * ui_home;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Button7;


// SCREEN: ui_setting
void ui_setting_screen_init(void);
lv_obj_t * ui_setting;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Switch6;
lv_obj_t * ui_Switch7;
lv_obj_t * ui_Switch8;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label15;


// SCREEN: ui_success
void ui_success_screen_init(void);
lv_obj_t * ui_success;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_line;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label16;


// SCREEN: ui_step1
void ui_step1_screen_init(void);
lv_obj_t * ui_step1;
lv_obj_t * ui_Button12;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Image4;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_image_[1] = {&ui_img_image_17_png};
const lv_img_dsc_t * ui_imgset_rectangle_[1] = {&ui_img_rectangle_7_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_init();
    ui_setting_screen_init();
    ui_success_screen_init();
    ui_step1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_step1);
}
