// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_home
void ui_home_screen_init(void);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button7;
// SCREEN: ui_setting
void ui_setting_screen_init(void);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Switch7;
extern lv_obj_t * ui_Switch8;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label15;
// SCREEN: ui_success
void ui_success_screen_init(void);
extern lv_obj_t * ui_success;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_line;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label16;
// SCREEN: ui_step1
void ui_step1_screen_init(void);
extern lv_obj_t * ui_step1;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_image_17_png);    // assets/image 17.png
LV_IMG_DECLARE(ui_img_corect_png);    // assets/corect.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_beer_corona_png);    // assets/beer_corona.png
LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_rectangle_7_png);    // assets/Rectangle 7.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
